INSERT INTO USERS(USERNAME, PASSWORD) VALUES('chobi', 'chobichobi');
INSERT INTO USERS(username, password) values('mikoshi','0408');

INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('タイトル1', '著者1', '出版社1', '2024-01-01');
INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('タイトル2', '著者2', '出版社2', '2024-01-01');
INSERT INTO BOOKS(TITLE, AUTHOR, PUBLISHER, PUBLISH_DATE) VALUES ('タイトル3', '著者3', '出版社3', '2024-01-01');

